### PR TITLE
Use go mods

### PR DESCRIPTION
**Pull request by ashu8912**
Switch to go modules 

We were using glide for package management, This pr replaces glide with go modules also removes the unnecessary vendors but still keeps the gensupport package as vendor as that package was dropped off from golang.org but our project still uses it.

# How to use
run make all to build the project 

# Testing done
Tested the project by pinging the Nebraska server with the generated build of the updateservicectl cli
To run that test i used 
./updateservicectl instance fake --clients-per-app
=500 --min-sleep=1 --max-sleep=50 --app-id=e96281a6-d1af-4bde-9a0a-97b76e56dc57 --group-id=beta --version=1.0.0

### CODE REVIEW

**Comment by ashu8912** [comment]
fixes #1

**Review by invidian — APPROVED** [review]
LGTM (but I'm not the maintainer :smile:)

**Comment by dongsupark** [comment]
Thanks for the PR. I am ok with using go mods.

However, the base branch should be `flatcar-master` instead of `master`.
Sorry, I have not noticed, the base branch has been set to `master` until now.
I have just set the default branch to `flatcar-master`, so further PRs should be automatically based on `flatcar-master`.

**Comment by ashu8912** [comment]
@dongsupark updated the base branch for this pr

**Review by dongsupark — APPROVED** [review]

**Pull request merged**
